### ISSUE TITLE
TODO: Criar a documentação dos arquivos .map e tilesets.

### ISSUE THREAD

**Issue by lorencinibrdev** [AdoriaStudios/Bomberbro#1]

**Comment by lorencinibrdev** [comment]
A estrutura do arquivo .map é formada da seguinte maneira:

######################## EXEMPLO DE ARQUIVO ########################
Normal Stage
13 11
1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0
1,0  ; 0,0  ; 0,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 0,0  ; 0,0  ; 1,0
1,0  ; 0,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 0,0  ; 1,0
1,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 1,0
1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 0,0  ; 1,0  ; 0,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0
1,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 0,0  ; 0,0  ; 0,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 1,0
1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 0,0  ; 1,0  ; 0,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0
1,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 1,0
1,0  ; 0,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 2,0  ; 1,0  ; 0,0  ; 1,0
1,0  ; 0,0  ; 0,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 2,0  ; 0,0  ; 0,0  ; 1,0
1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0  ; 1,0
######################## FIM DE ARQUIVO ########################

Nesse arquivo, temos as seguintes estruturas:

-> Na primeira linha, temos o nome do estágio. Esse nome será exibido dentro do seletor de mapas do jogo.

-> Na segunda linha, temos o tamanho desse mapa, representado, em TILES, por dois inteiros (W,H) separados por espaços, onde W = Largura e H = Altura.

-> Da terçeira linha até o EOF (Fim Do Arquivo), temos a estrutura do mapa propriamente dita. 

Cada TILE é representado por um conjunto de números, separados por ',' (vírgulas), onde o primeiro número corresponde ao tipo base do TILE, ou seja, se ele é um CHÃO ('0', Passável), uma PAREDE QUEBRÁVEL ('2', Não Passável) ou uma PAREDE FIXA ('3', Não Passável).

Os outros números dentro da estrutura do TILE são responsáveis por indicar para a engine a posição do frame da animação que compõe o TILE. No exemplo acima, todos os tiles possuem apenas UM frame, portanto, todos são seguidos de zero.

A divisão entre os TILES, por sua vez, ocorre usando-se o caractere ';' (Ponto e Vírgula), de forma a indicar para a engine que o tile atual deve ser salvo, e o próximo deve ser iniciado.

Creio estar tudo explicado. Lembrando que toda e qualquer manipulação dos arquivos '.map' devem ser realizados SOMENTE no MapEditor do jogo (ver ISSUE #2 ).

Se estiver OK com o resto do grupo, fecharei esse Issue.

**Comment by cadumancini** [comment]
Estou de acordo sim. Está tudo muito bem explicado.
Sobre o thumbnail do mapa para o seletor, como fica? Será tratado na issue do MapEditor?

**Comment by lorencinibrdev** [comment]
Sim. Trataremos ela no Editor de mapas. 

Esse Issue será fechado.
