### ISSUE TITLE
Reestruturação do Projeto (C++ -> C#)

### ISSUE THREAD

**Issue by lorencinibrdev** [AdoriaStudios/Bomberbro#18]
Hoje, iniciei a reestruturação do projeto, para utilizarmos agora a linguagem C# e a Bilbioteca Monogame para desenvolvemento do mesmo, visto que essa configuração permite uma melhor expanção para mercados mobile e Web futuramente.

**Comment by lorencinibrdev** [comment]
O sistema de Estados do jogo já foi passado pra C#, assim como a engine principal.

O projeto já pode ser inicializado, porém ele ainda não entra em um novo jogo.

**Comment by lorencinibrdev** [comment]
O sistema de bombas, envolvendo seus timers, criação de fogos e animações, está implementado.

Também foi implementado o sistema de quebra de paredes, usando a bomba.

**Comment by Flazey** [comment]
Correção necessária: a bomba pode ser colocada sobre os blocos indestrutíveis da fase, tanto dentro do campo quanto nas paredes limitadoras da fase.

**Comment by lorencinibrdev** [comment]
Opa! É intencional por enquanto. :)

Na verdade, não é intencional, mas eu tinha notado o erro. Só não fiz as verificações pra impedir isso ainda pq, na versão final, não será possivel usar o mouse pra instalar bombas.

Mas agradeço o toque.

**Comment by lorencinibrdev** [comment]
A transição para C# está agora completa, restando apenas Otimizações de código.
