### ISSUE TITLE
Cria Bomba e sua Chama

### ISSUE THREAD

**Issue by EduardoSpinelli** [AdoriaStudios/Bomberbro#23]
Esta etapa é essencial para o jogo, pois é o item principal para que ocorra as devidas jogabilidades. Como discutindo no Issues de criação de ideias, sera necessário criar face para as bombas,  Ex; Um olho normal, conforme ela for chegando no limite de explosão, ela fica brava e vermelha. 
Mas é uma ideia que pode ser alterada por qualquer outra ideia.

**Comment by Flazey** [comment]
Elaborada primeira versão da bomba comum para o game. Segue o link para visualização de .gif modelo http://oi68.tinypic.com/r08bcw.jpg
Link para arquivos no drive https://drive.google.com/open?id=0B1cuo9QXZSTuWmNnb0MtWjNkM2M
![teste_tela_explosao](https://cloud.githubusercontent.com/assets/16062207/11916221/46a50586-a6b4-11e5-983b-a6ecfc19f577.png)

**Comment by EduardoSpinelli** [comment]
Parabéns cara ficou muito bom este modelo, com o tempo a gente vai aperfeiçoando nosso jogo para ficar mais bonito!

**Comment by lorencinibrdev** [comment]
Guilherme, parabéns! Ficou muito bom.

Esses efeitos na lateral do fogo ficaram 10. Boa sacada.

Vou ver se consigo dar uma adiantada na programação, pra compensar a miniférias do casamento.

Assim a gente consegue ver esses novos gráficos implementados.

Parabéns a toda a equipe!

**Comment by Flazey** [comment]
Sprite sheet da bomba inicial e seus níveis de explosão

![sprites objetos](https://cloud.githubusercontent.com/assets/16062207/12225250/88084142-b7ed-11e5-99be-662fa8a33dde.png)

**Comment by lorencinibrdev** [comment]
Fechando esse issue, pois a bomba e os Fogos estão devidamente implementados.
