### ISSUE TITLE
BUG detectado: SegFault

### ISSUE THREAD

**Issue by cadumancini** [AdoriaStudios/Bomberbro#8]
Em certos momentos, ao estourar várias bombas juntas, está dando SegFault. O erro não é frequente, funcionando tudo normalmente na grande maioria das vezes, tornando difícil a reprodução do mesmo.

**Comment by lorencinibrdev** [comment]
Conforme conversado, é preciso usar o Debugger (F8) SEMPRE que formos realizar qualquer teste. Assim, quando o segFault aparecer, saberemos de onde veio.

**Comment by cadumancini** [comment]
Foi percebida a ocorrência do SegFault alguns momentos ao plantar a bomba, na função que passa o currentTile para o BombManager. Nas vezes em que o bug ocorre, é porque está passando o tile atual como NULL. Somente em um ponto do código, o tile pode ser setado para NULL. A correção será feita, e o resultado será reportado aqui.

**Comment by cadumancini** [comment]
Aparentemente, o problema está resolvido. Vou deixar a issue aberta por enquanto, para realizarmos mais testes. Se nos próximos dias o erro não voltar a ocorrer, fecho essa issue.

**Comment by cadumancini** [comment]
Após a correção, esse SegFault não voltou mais a ocorrer. Issue encerrada.
